# Generated by Django 4.0.1 on 2022-02-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message_subject_alter_message_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
